### ISSUE TITLE
数据上下拉加载

### ISSUE THREAD

**Issue by Hewang-github** [huangyanbin/smartTable#1]
smartTable在交互上体验还是很棒的，也属于列表类型的控件，若有需求在数据很多的情况下，就得考虑分页加载的问题，建议大神可以扩展集成下分页加载 @huangyanbin

**Comment by huangyanbin** [comment]
终于有人用了，非常感谢，写了几天没白写！我也想过这个问题，但只要你将请求获取数据add到之前数据List 上去，然后notifyDataChanged就可以基本满足了。但是我只测试过几千数据，不过够用了。没有显示在屏幕上的也不会绘制。使用普通模式，记得不要混淆bean。关于分页加载进度条，这个暂时没计划。帮忙点个star,谢谢！

-
