### ISSUE TITLE
QQ群搜不到啊

### ISSUE THREAD

**Issue by AndMy** [huangyanbin/smartTable#100]
QQ群搜不到啊

**Comment by zhangjie201412** [comment]
帅哥，有遇到过编译报错吗，我使用AS 3.1版本
Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

Failed to resolve: com.github.huangyanbin:SmartTable:2.2.0
Show in File
Show in Project Structure dialog

**Comment by huangyanbin** [comment]
可以重新fork修改一下
