### ISSUE TITLE
数据更新时有几率不会刷新页面，需要点击table才会刷新

### ISSUE THREAD

**Issue by zengxiangcai** [huangyanbin/smartTable#111]
你好，使用时发现个问题，不知道是不是我这边问题。页面有个筛选弹出框，选择条件之后，重新请求数据，来回切换时有概率不会及时更新页面，需要点击下table才会刷新过来，

**Comment by zengxiangcai** [comment]
@huangyanbin

**Comment by missLFY** [comment]
我也遇到了这个问题，不知道怎么解决，各位大佬求教！！

**Comment by missLFY** [comment]
> 你好，使用时发现个问题，不知道是不是我这边问题。页面有个筛选弹出框，选择条件之后，重新请求数据，来回切换时有概率不会及时更新页面，需要点击下table才会刷新过来，

我也遇到了这个问题，不知道怎么解决，你那边解决了吗？如果解决了，求教方法，谢谢！！
