### ISSUE TITLE
有没有方法可以清屏？

### ISSUE THREAD

**Issue by chenliang1937** [huangyanbin/smartTable#113]
有没有方法可以清除表格中的数据？

**Comment by yyy000112** [comment]
有啊，把item和column集合clear之后，notifyChange就可以了

**Comment by EFGL** [comment]
有没有清空的demo ,找方法都找不见

**Comment by LIUPING789** [comment]
爆力美学，直接用 table!!.visibility = View.VISIBLE  or View.GONE
