### ISSUE TITLE
【bug】不显示表名，且行数不占满屏幕，滑动时统计行的内容被该行背景色覆盖

### ISSUE THREAD

**Issue by JakeWoki** [huangyanbin/smartTable#124]

**Comment by JakeWoki** [comment]
https://github.com/huangyanbin/smartTable/issues/104

**Comment by JakeWoki** [comment]
https://github.com/huangyanbin/smartTable/pull/135/commits/d126544f12278209842528557c65cd60282755ab
已修复

**Comment by JakeWoki** [comment]
这是修复还是不修复？@huangyanbin

**Comment by SheepYang1993** [comment]
试试设置wrap_content
