### ISSUE TITLE
关于smartTable的混淆 ，请会的大佬帮帮忙

### ISSUE THREAD

**Issue by xi5528336** [huangyanbin/smartTable#126]
有哪位大哥能够给一下 smartTable的混淆demo，正式打包后  总是报错：NoSuchFieldException :Please check whether field name is correct。

**Comment by weixinzhi003** [comment]
> 有哪位大哥能够给一下 smartTable的混淆demo，正式打包后 总是报错：NoSuchFieldException :Please check whether field name is correct。

-keep class com.bin.david.form.** { *; }

**Comment by huangyanbin** [comment]
你必须keep 你的bean类不混淆

**Comment by geoLei** [comment]
我也遇到同样的问题，请问您能不能在GitHub里写明下，方便初学者应用哈
