### ISSUE TITLE
请问如何设置每列的宽度?

### ISSUE THREAD

**Issue by yygutn** [huangyanbin/smartTable#13]
RT,我试过覆写IDrawFormat$measureWidth,但是不行.

**Comment by huangyanbin** [comment]
你贴下你复写的代码

**Comment by yygutn** [comment]
代码在家,,,,,我写一个类似的吧....

![image](https://user-images.githubusercontent.com/8274198/35657702-ccdbc73e-0738-11e8-9dfe-638c7cc80685.png)

**Comment by huangyanbin** [comment]
经过测试是没有问题的，因为默认格子有padding，padding横向默认是40px.两边就是80。格子大小是测量大小measureWidth+padding*2。加上图片大小，当你设置35dp你感觉不到细微变化，你可以设置100 dp试试。当然你也可以 `将j把横向的padding都设置为0,`table.getConfig().setHorizontalPadding(0);` table.getConfig().setColumnTitleHorizontalPadding(0);`这样看到变化了。

**Comment by yygutn** [comment]
嗯嗯....谢谢,我晚上回去试试

**Comment by huangyanbin** [comment]
你可以设置一个固定的padding值哈，你需要宽度减掉padding 设置给measureWidth，一般情况下宽度都是动态计算出来的，毕竟在App显示，这样尽量保持表格的美观。measureWidth重写的机会很少的。
