### ISSUE TITLE
数据更新时不会自动刷新页面，需要点击table才会刷新

### ISSUE THREAD

**Issue by missLFY** [huangyanbin/smartTable#153]
你好，使用时发现个问题，不知道是不是我这边问题。页面有个查询按钮，重新请求数据，来回切换时有概率不会及时更新页面，需要点击下table才会刷新过来，怎么解决这个刷新的问题，求教！！！

**Comment by yihaha** [comment]
同样遇到,请问解决了吗 ?

**Comment by johnnylfq** [comment]
同问

**Comment by guanhaobo** [comment]
+1

**Comment by guanhaobo** [comment]
table.invalidate();
这个是用来通知table刷新的的
