### ISSUE TITLE
List解析成多个Column

### ISSUE THREAD

**Issue by kingyangcn** [huangyanbin/smartTable#16]
刚看到增加了List的解析，但是是解析到一个Column里面的。很多使用场景是需要将一个List解析成多个Column进行展示，希望添加，非常感谢。

**Comment by huangyanbin** [comment]
可以解析到多个列里面去，还有一些细节未完成

**Comment by kingyangcn** [comment]
@huangyanbin 具体怎么做的呢，能大概说一下吗

**Comment by huangyanbin** [comment]
![qq 20180203135607](https://user-images.githubusercontent.com/6211094/35763569-18c5ebf4-08ea-11e8-85c4-d73833c4f55e.png)
![qq 20180203135631](https://user-images.githubusercontent.com/6211094/35763570-18fbf316-08ea-11e8-8fc3-ee88144d358c.png)
功能完善估计还要等几天，现在你可以下载最新代码，看下demo有示例。不过还不是很完善。

**Comment by kingyangcn** [comment]
好的，万分感谢。

**Comment by huangyanbin** [comment]
完成了List 转列，你看下是否可以使用https://juejin.im/post/5a7a8eef5188257a84621eda

**Comment by tangxunT** [comment]
请问List转成多个Column现在增加解决方法了吗
