### ISSUE TITLE
请问支持上拉加载吗?

### ISSUE THREAD

**Issue by kona5362** [huangyanbin/smartTable#17]
看到有分页，但是似乎没有上拉加载，
还有字体除了大小颜色,还能设置其他属性吗?比如textStyle

最后赞叹一下，非常强大的控件。

**Comment by huangyanbin** [comment]
上拉加载有，使用其他控件完成的，demo中，你如果想支持更多样式，你可以重写IDrawFormat，这个有点复杂，或者重新IDrawFormat子类 TextDrawFormat例如：TextDrawFormat.public void setTextPaint(TableConfig config,T t, Paint paint)即可设置更多样式。

**Comment by kona5362** [comment]
好的我仔细研究下
