### ISSUE TITLE
2.2版的设置格子背景不生效，readme里的demo链接打不开

### ISSUE THREAD

**Issue by xfdr0805** [huangyanbin/smartTable#174]
table.getConfig().setColumnCellBackgroundFormat(new ICellBackgroundFormat<Column>() {
            @Override
            public void drawBackground(Canvas canvas, Rect rect, Column column, Paint paint) {
                paint.setColor(Color.argb(128,0,255,0));
                canvas.drawRect(rect,paint);
            }
            @Override
            public int getTextColor(Column column) {
                return 0;
            }
        });

**Comment by xfdr0805** [comment]
应该用
table2.getConfig().setContentCellBackgroundFormat(new ICellBackgroundFormat<CellInfo>() {
            @Override
            public void drawBackground(Canvas canvas, Rect rect, CellInfo cellInfo, Paint paint) {
                if(cellInfo.col == 4 && cellInfo.row == 3){
                    paint.setColor(Color.argb(128,0,255,0));
                    canvas.drawRect(rect,paint);
                }

            }

            @Override
            public int getTextColor(CellInfo cellInfo) {
                return 0;
            }
        });

**Comment by xfdr0805** [comment]
这样为什么只绘制出来了一个
table2.getConfig().setContentCellBackgroundFormat(new ICellBackgroundFormat<CellInfo>() {
            @Override
            public void drawBackground(Canvas canvas, Rect rect, CellInfo cellInfo, Paint paint) {
                if(cellInfo.value.isEmpty()){
                    paint.setColor(Color.argb(128,0,255,0));
                    canvas.drawRect(rect,paint);
                }

            }

            @Override
            public int getTextColor(CellInfo cellInfo) {
                return 0;
            }
        });

**Comment by Scott110** [comment]
`public class TitleDrawFormat implements ITitleDrawFormat {

public boolean drawBackground(Canvas c, Column column, Rect rect,  TableConfig config) {
        ICellBackgroundFormat<Column> backgroundFormat = config.getColumnCellBackgroundFormat();
        if(isDrawBg && backgroundFormat != null ){
            backgroundFormat.drawBackground(c,rect,column,config.getPaint());
            return true;
        }
        return false;
    }`
isDrawBg 需要设置

**Comment by muyoumingzi** [comment]
> `public class TitleDrawFormat implements ITitleDrawFormat {
> 
> public boolean drawBackground(Canvas c, Column column, Rect rect, TableConfig config) {
> ICellBackgroundFormat backgroundFormat = config.getColumnCellBackgroundFormat();
> if(isDrawBg && backgroundFormat != null ){
> backgroundFormat.drawBackground(c,rect,column,config.getPaint());
> return true;
> }
> return false;
> }`
> isDrawBg 需要设置

这个只是标题网格的线颜色变了，内容背景色没变啊，感觉像是被覆盖了！
