### ISSUE TITLE
嵌套在scrollerview中未能全部显示

### ISSUE THREAD

**Issue by guxun12** [huangyanbin/smartTable#18]
请问在scrollerview中使用smartTable的正确姿势是什么？

**Comment by huangyanbin** [comment]
你先写死高度，
`   <com.bin.david.form.core.SmartTable
       android:id="@+id/table"
       android:layout_width="match_parent"
       android:layout_height="600dp"

      />`
我刚发现这个问题。我下个更新修复它。

**Comment by guxun12** [comment]
谢谢回复。
目前我是动态设置LayoutParams.height来尽量避免UI变形的，每行高度30dp，计算的不精确。

**Comment by huangyanbin** [comment]
我刚修复了这个问题，稍等一会，我先测试一下，看下是否完全OK了。等下就提交发版本

**Comment by huangyanbin** [comment]
1.8.1已经修复，你可以使用wrapContent来设置高度，会自动计算高度的，表格不会超过屏幕的高度-它开始的View。你可以替换试试

**Comment by guxun12** [comment]
更新后正常显示了👍

**Comment by 594238813** [comment]
lifecycleScope.launch {
            delay(1000)

            val tableHeight = tableDataView?.getTableData()?.getTableInfo()?.getTableRect()?.bottom;

            // 设置 LayoutParams
            val lp = tableDataView?.layoutParams
            if (tableHeight != null) {
                lp?.height = tableHeight
            }
            tableDataView?.layoutParams = lp
        }     我是放在viewpager2-NestedScrollview， 高度显示有点问题，可以延迟1s在 测量
