### ISSUE TITLE
导入excel

### ISSUE THREAD

**Issue by yswheye** [huangyanbin/smartTable#19]
17. 导入excel(支持颜色，字体，背景，批注，对齐，图片等基本Excel属性)
这个功能在哪，没找到呀

**Comment by yswheye** [comment]
顺便问一下，能导出为excel么

**Comment by huangyanbin** [comment]
不能导出Excel，导出Excel你可以使用jxl或者poi，导入excel请参考demo代码。你可以下个demo先看看

**Comment by yswheye** [comment]
.xlsx格式的导入不支持吗？

**Comment by huangyanbin** [comment]
导入是通过jxl和poi实现，获取数据和样式设置给表格，.表格只负责显示，数据来源可以任意。你可以自己实现BaseExcel2Table来实现其他的格式。
我没有发现很好框架对xlsx支持，poi xlsx包太大了，jxl不支持xlsx

**Comment by yswheye** [comment]
好的，多谢

**Comment by huangyanbin** [comment]
如果你发现有对xlsx支持比较好的，我顺便把示例写在demo里面。
