### ISSUE TITLE
怎么单独设置Column的背景

### ISSUE THREAD

**Issue by kingyangcn** [huangyanbin/smartTable#21]
需求是根据值设置cell的背景，值不为空的cell将其背景设置为红色。代码如下，得到的结果是所有cell都变红色了，并且覆盖了文本值。
`column4.setDrawFormat(new TextDrawFormat<String>() {

            @Override
            public void drawBackground(Canvas c, CellInfo<String> cellInfo, Rect rect, TableConfig config) {
                if (!TextUtils.isEmpty(cellInfo.value)) {
                    c.drawColor(Color.RED);
                }
            }
        });`

**Comment by huangyanbin** [comment]
绘制单个 格子背景是
`
Paint paint = config.getPaint();
paint.setColor(color);
            paint.setStyle(Paint.Style.FILL);
            canvas.drawRect(rect, paint);`
不是drawColor
你是重写的TextDrawFormat drawBackground方法，其实有专门设置背景的和改变字体颜色的。
 table.getConfig().setContentBackgroundFormat(new BaseCellBackgroundFormat<CellInfo>() {
            @Override
            public int getBackGroundColor(CellInfo cellInfo) {
               
                //根据cellInfo.column需要返回不同背景颜色
                return TableConfig.INVALID_COLOR;
            }

            @Override
            public int getTextColor(CellInfo cellInfo) {
                //根据cellInfo.column需要返回不同字体颜色
                return TableConfig.INVALID_COLOR;
            }
        });

**Comment by kingyangcn** [comment]
@huangyanbin 如果要绘制自定义背景该怎么写呢？

**Comment by kingyangcn** [comment]
知道了，之前也看到这个方法了，没发现可以通过cell.column得到列的信息，以为只能对所有列统一处理。感谢

**Comment by kingyangcn** [comment]
@huangyanbin BaseCellBackgroundFormat只有getBackGroundColor，没有getBackGroundDrawable之类的，要怎么实现呢

**Comment by huangyanbin** [comment]
你想要绘制图片之类的，必须用实现ICellBackgroundFormat接口，然后自己绘制图片，绘制图片很简单，网上一大堆。

**Comment by kingyangcn** [comment]
好的。真是太感谢了
