### ISSUE TITLE
setData设置数据时，字段可以为null，而addData添加数据时字段为null就会空指针异常

### ISSUE THREAD

**Issue by kona5362** [huangyanbin/smartTable#22]
这一点有点疑问

**Comment by huangyanbin** [comment]
你贴下报错信息

**Comment by kona5362** [comment]
![image](https://user-images.githubusercontent.com/28619342/36018548-1c77f914-0db7-11e8-96d2-6156dd0baab5.png)

**Comment by kona5362** [comment]
还有一个小问题：控件高度好像一直是match_parent，是否能根据条目数量决定呢
感谢解答

**Comment by huangyanbin** [comment]
可以设置wrapcontent的，但是adddata改变高度没试过

**Comment by huangyanbin** [comment]
你设置wrapcontent 宽度会跟随addData变化,直到宽度等于MatchParent不会再增加。你试试1.8.4

**Comment by kona5362** [comment]
好的，感谢

不过改成1.8.4后找不到包。
![image](https://user-images.githubusercontent.com/28619342/36081410-65dc816e-0fd9-11e8-89c9-3d8a11867046.png)
发现1.84的jars的classes.jar里面是空的,换了个项目也是这样。
不知道是不是我这边的问题，回去我再用自己电脑试试
![image](https://user-images.githubusercontent.com/28619342/36081432-9838fe6c-0fd9-11e8-81c9-011519e92c5a.png)
![image](https://user-images.githubusercontent.com/28619342/36081442-bd99b7f0-0fd9-11e8-8388-91cc9626347c.png)

**Comment by huangyanbin** [comment]
不知道为啥，jitpack突然打包就不行了，你如果需要的话，可以直接去Release下载最新集成包试试

**Comment by huangyanbin** [comment]
1.8.7可以用了
