### ISSUE TITLE
1.8.3版本下载不下来

### ISSUE THREAD

**Issue by guxun12** [huangyanbin/smartTable#23]
你好，更新版本到1.8.3发现gradle没有下载成功。
缓存中的smarttable-1.8.3.aar文件为1kb，并且没有下载到对应的pom文件。
使用旧版本号（比如1.6.3）就是正常的。

**Comment by huangyanbin** [comment]
稍等，我等下重新发给包。

**Comment by huangyanbin** [comment]
不知道为啥，jitpack突然打包就不行了，你如果需要的话，可以直接去Release下载最新集成包试试

**Comment by huangyanbin** [comment]
1.8.7可以了，你试试
