### ISSUE TITLE
如何设置表格每一行的背景颜色

### ISSUE THREAD

**Issue by lijinzedev** [huangyanbin/smartTable#241]
没有找到设置行的方法

**Comment by LuoCang** [comment]
同问

**Comment by HonestMan123** [comment]
> 同问
我最近也在搞这个，找到了解决办法，不知道你适不适用
mTableView.getConfig().setContentCellBackgroundFormat(new ICellBackgroundFormat<CellInfo>() {
            @Override
            public void drawBackground(Canvas canvas, Rect rect, CellInfo cellInfo, Paint paint) {
                     //如果每一行的背景色都是相同的话，可以这样
                     paint.setColor(ContextCompat.getColor(context, R.color.colorLine));
                    canvas.drawRect(rect, paint);
                  //如果你想设置每一行不同颜色的话，可以根据cellInfo里面相应的值去判断
}

**Comment by LuoCang** [comment]
> > 同问
> > 我最近也在搞这个，找到了解决办法，不知道你适不适用
> > mTableView.getConfig().setContentCellBackgroundFormat(new ICellBackgroundFormat() {
> > @override
> > public void drawBackground(Canvas canvas, Rect rect, CellInfo cellInfo, Paint paint) {
> > //如果每一行的背景色都是相同的话，可以这样
> > paint.setColor(ContextCompat.getColor(context, R.color.colorLine));
> > canvas.drawRect(rect, paint);
> > //如果你想设置每一行不同颜色的话，可以根据cellInfo里面相应的值去判断
> > }

谢谢 我也这么解决了

**Comment by lijinzedev** [comment]
> > 同问
> > 我最近也在搞这个，找到了解决办法，不知道你适不适用
> > mTableView.getConfig().setContentCellBackgroundFormat(new ICellBackgroundFormat() {
> > @override
> > public void drawBackground(Canvas canvas, Rect rect, CellInfo cellInfo, Paint paint) {
> > //如果每一行的背景色都是相同的话，可以这样
> > paint.setColor(ContextCompat.getColor(context, R.color.colorLine));
> > canvas.drawRect(rect, paint);
> > //如果你想设置每一行不同颜色的话，可以根据cellInfo里面相应的值去判断
> > }

谢谢大佬
