### ISSUE TITLE
double类型的字段没有自动统计

### ISSUE THREAD

**Issue by EpicWang** [huangyanbin/smartTable#25]
新年快乐，我看了下源码，setCountFormat中是处理了double和float的，但是我double类型的字段没有自动统计
![tim 20180222191516](https://user-images.githubusercontent.com/15323264/36535757-ab0c3d40-1805-11e8-9f1c-dafb87dc5cd2.png)

![tim 20180222191807](https://user-images.githubusercontent.com/15323264/36535745-a30f7530-1805-11e8-9523-20677d7a2c2b.png)

**Comment by huangyanbin** [comment]
已修复 1.8.8
