### ISSUE TITLE
setAutoMerge(true)有的无效呢？

### ISSUE THREAD

**Issue by mtjsoft** [huangyanbin/smartTable#26]
所有的列都设置了.setAutoMerge(true);。列的5、6两行合并了。同一列下面的8、9、10、11行也是相同的内容，为什么没有自动合并呢？好奇怪

**Comment by huangyanbin** [comment]
给我看下你数据

**Comment by mtjsoft** [comment]
![default](https://user-images.githubusercontent.com/25857540/36715960-9535965c-1bd3-11e8-9737-fc70fd1b0fc9.png) 从这个Excel读取的数据。前两列，行数据为空时，取上一行的数据显示。5、6的前两列合并成了一个1.3。但是8、9、10、11的第一列都显示2.1，没有合并。

**Comment by mtjsoft** [comment]
![default](https://user-images.githubusercontent.com/25857540/36716299-d0a2009e-1bd4-11e8-9ff7-2d7dccb7093d.png)
这个是我显示的数据。你看看。感谢。

**Comment by huangyanbin** [comment]
你为啥不直接用表格模式哈

**Comment by mtjsoft** [comment]
![default](https://user-images.githubusercontent.com/25857540/36716441-56f2e988-1bd5-11e8-83bd-0b4bd7ae3e66.png)
请问一下，表格模式，可以在最后一列加入选择吗？刚要你的框架。还不熟悉啊

**Comment by mtjsoft** [comment]
大神，怎么不弄一个交流群，也方便一下我们学习啊。

**Comment by huangyanbin** [comment]
QQ群724699041

**Comment by tangxunT** [comment]
> QQ群724699041

这个群加不了啊
