### ISSUE TITLE
如何设置列的宽度

### ISSUE THREAD

**Issue by meijingkang** [huangyanbin/smartTable#29]
请问,如何设置列的宽度

**Comment by meijingkang** [comment]
经作者提示
``
 final Column<String> ageColumn = new Column<>("年龄",
                    "age",new MultiLineDrawFormat<String>(screenWith - columWidth));
``
感谢开源作者

**Comment by cheng2zheng1314** [comment]
设置完之后，高度变高了 请问怎么解决的
