### ISSUE TITLE
内容换行

### ISSUE THREAD

**Issue by androidShuang** [huangyanbin/smartTable#3]
您好，我需求是在内容里面，固定宽度，然后内容会自动换行，今天改了点代码，但是文字并不居中，不知道需要有哪些类需要改动？

**Comment by huangyanbin** [comment]
您好，暂时没有这功能，主要是因为没人使用。如果你觉得好用的话，帮忙点个Star。我稍后把这个内容自动换行功能补充上去。

**Comment by huangyanbin** [comment]
已提交增加了内容换行，请参考最近代码Column.setDrawFormat(new MultiLineDrawFormat<String>(this,dp));

**Comment by Selina592732122** [comment]
final Column<Integer> type1Column = new Column<>("智能终端总数量（台）", "type1");
type1Column.setDrawFormat(new MultiLineDrawFormat(this,5));

好像没换行 是为什么？
