### ISSUE TITLE
how change row text

### ISSUE THREAD

**Issue by crazecoder** [huangyanbin/smartTable#31]

**Comment by huangyanbin** [comment]
Now you can't edit table data for the time being. If you want to change the data, you can modify the value by modifying the code Column.getData().Set (position, data).

**Comment by crazecoder** [comment]
I mean YSequence text

**Comment by huangyanbin** [comment]
You can use it   `table.getTableData().setYSequenceFormat(ISequenceFormat format); Implement interface method` lString format(int number);` Number stands for the serial number, and the return value is the display character

**Comment by crazecoder** [comment]
I did as you said.It worked ,but the YSequence width is small,Is the width fixed?

**Comment by huangyanbin** [comment]
table.getConfig().setSequenceHorizontalPadding(50);

**Comment by d8txc** [comment]
能否增加 隐藏列的功能
