### ISSUE TITLE
after refresh data, the UI of table reduce a row

### ISSUE THREAD

**Issue by CamiYe** [huangyanbin/smartTable#33]
I need to change a column's data, when I call column.getDatas().set(position, true); and then call table.invalidate(); the UI of table reduce a row,  why? Is it a exception? or I call error functions.

**Comment by huangyanbin** [comment]
I pressed your feedback and tried not to find this problem. Can you post the code?

**Comment by CamiYe** [comment]
I had resolved the issue, the reason is I don't set the SmartTable's layout of height is match-parent.
