### ISSUE TITLE
ArrayTableData.create() BUG反馈

### ISSUE THREAD

**Issue by moetaku** [huangyanbin/smartTable#38]
/**
     * 创建二维数组表格数据
     * 如果数据不是数组[row][col]，可以使用transformColumnArray方法转换
     * @param tableName 表名
     * @param titleNames 列名
     * @param data 数据 数组[row][col]
     * @param drawFormat 数据格式化
     * @return 创建的二维数组表格数据
     */
    public static<T> ArrayTableData<T> create(String tableName,String[] titleNames, T[][] data, IDrawFormat<T> drawFormat){
        List<Column<T>> columns = new ArrayList<>();
        for(int i = 0;i <data.length;i++){
            T[] dataArray = data[i];
            Column<T> column = new Column<>(titleNames == null?"":titleNames[i], null,drawFormat);
            column.setDatas(Arrays.asList(dataArray));
            columns.add(column);
        }
        ArrayList<T> arrayList = new ArrayList<>(Arrays.asList(data[0]));
        ArrayTableData<T> tableData =  new ArrayTableData<>(tableName,arrayList,columns);
        tableData.setData(data);
        return tableData;
    }

注释写传入的参数二维数组为[row][col]，在方法体里的处理却是按照数组[col][row]进行处理。

若二维数组data[m][n]，理解为一个m行，n列的二维数组，则data.length等于m，data[i].length等于n，data[i]为i行的一维数组数据，即i行的所有列数据。

        for(int i = 0;i <data.length;i++){
            T[] dataArray = data[i];
            Column<T> column = new Column<>(titleNames == null?"":titleNames[i], null,drawFormat);
            column.setDatas(Arrays.asList(dataArray));
            columns.add(column);
        }
循环体里按行取数据，然后在表格里作为一列的数据使用，这就对数据做了行列交换处理。

**Comment by huangyanbin** [comment]
注释写反了，有人也反馈这个问题。ArrayTableData也提供了对二维数组进行转换方法

**Comment by Linger50** [comment]
入参数组应该是 data[col][row] 格式，data[0] 为一列的数据，column.setDatas(Arrays.asList(dataArray));就是把一列的数据传入到column中
