### ISSUE TITLE
请问是否将来支持读取excel表格并显示数据

### ISSUE THREAD

**Issue by onexuan** [huangyanbin/smartTable#4]
请问是否将来支持读取excel表格并显示数据

**Comment by onexuan** [comment]
非常开心看到如何强大的开源库！

**Comment by onexuan** [comment]
我看到你的网络模式，“地区”是显示合并的，"PM"也有合并的，你指的是更复杂的合并？希望作者支持

**Comment by huangyanbin** [comment]
地区是一个普通的子列，而PM是组合列的，在注解模式中parent 代表它有父列，如果没有parent，代表只要没有父列。

**Comment by onexuan** [comment]
那如果用解析模式，可以用父列？

**Comment by huangyanbin** [comment]
注解模式只支持父列，父列不能再组合了。但是普通模式下，任意组合，可以组合N层。

**Comment by onexuan** [comment]
明白，在思考如何从一个不确定的表（比如html的table，excel的表），转成现在你这个库的表，作者可以给点思路吗？

**Comment by huangyanbin** [comment]
你加下我QQ，873825232，聊一聊你的想法。我一直想实现能否加载List 里面有List的数据展示。
