### ISSUE TITLE
dialogfragment 中使用异常

### ISSUE THREAD

**Issue by BIGMONK** [huangyanbin/smartTable#46]
# ## dialog dismiss的时候报错

05-16 19:54:36.185 21577-21577/? W/System.err: java.lang.ClassCastException: android.view.ContextThemeWrapper cannot be cast to android.app.Activity
05-16 19:54:36.185 21577-21577/? W/System.err:     at com.bin.david.form.core.SmartTable.onDetachedFromWindow(SmartTable.java:591)
05-16 19:54:36.185 21577-21577/? W/System.err:     at android.view.View.dispatchDetachedFromWindow(View.java:13690)
05-16 19:54:36.185 21577-21577/? W/System.err:     at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2834)
05-16 19:54:36.185 21577-21577/? W/System.err:     at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2834)
05-16 19:54:36.185 21577-21577/? W/System.err:     at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2834)
05-16 19:54:36.185 21577-21577/? W/System.err:     at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2834)
05-16 19:54:36.185 21577-21577/? W/System.err:     at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2834)
05-16 19:54:36.185 21577-21577/? W/System.err:     at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:3192)
05-16 19:54:36.185 21577-21577/? W/System.err:     at android.view.ViewRootImpl.doDie(ViewRootImpl.java:5776)
05-16 19:54:36.185 21577-21577/? W/System.err:     at android.view.ViewRootImpl.die(ViewRootImpl.java:5753)
05-16 19:54:36.185 21577-21577/? W/System.err:     at android.view.WindowManagerGlobal.removeViewLocked(WindowManagerGlobal.java:439)
05-16 19:54:36.185 21577-21577/? W/System.err:     at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:394)
05-16 19:54:36.185 21577-21577/? W/System.err:     at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:125)
05-16 19:54:36.185 21577-21577/? W/System.err:     at android.app.Dialog.dismissDialog(Dialog.java:341)
05-16 19:54:36.185 21577-21577/? W/System.err:     at android.app.Dialog.dismiss(Dialog.java:324)
05-16 19:54:36.185 21577-21577/? W/System.err:     at android.app.DialogFragment.dismissInternal(DialogFragment.java:278)
05-16 19:54:36.185 21577-21577/? W/System.err:     at android.app.DialogFragment.dismiss(DialogFragment.java:258)

**Comment by huangyanbin** [comment]
可以修改一下SmartTable的 OnDettachView方法

**Comment by xiangyuanStar** [comment]
我新建了一个类：MySmartTable，将SmartTable类里面的内容全部复制过来，并且将onDetachedFromWindow()方法中的if (((Activity) getContext()).isFinishing()) {}语句注释掉，然后使用MySmartTable类

**Comment by yuandoudou928** [comment]
我新建了一个类：MySmartTable，将SmartTable类里面的内容全部复制过来，并且将onDetachedFromWindow()方法中的if (((Activity) getContext()).isFinishing()) {}语句注释掉，然后使用MySmartTable类。
onDetachedFromWindow()方法是在Act destroy的时候被调用的，也就是act对应的window被删除的时候，且每个view只会被调用一次，父view的调用在后，也不论view的visibility状态都会被调用，适合做最后的清理操作；
