### ISSUE TITLE
发现一个小bug

### ISSUE THREAD

**Issue by Fozei** [huangyanbin/smartTable#48]
使用Form类中的静态变量Empty做多个占位的时候，改变一个占位的name，其他占位也会跟着变，所以这个变量应该去掉。

**Comment by huangyanbin** [comment]
你别用这个Empty去占位

**Comment by Fozei** [comment]
嗯，不用这个占位是没有问题的。我上来也没细看，修改数据的时候才发现的，建议把这个类变量移除。
