### ISSUE TITLE
小问题

### ISSUE THREAD

**Issue by xiemeng99** [huangyanbin/smartTable#5]
当放大之后，固定列的setFixedYSequence方法不生效了，而且无法滑动到最顶部和最左边了

**Comment by huangyanbin** [comment]
hi,我已经解决这个问题，还是发布Release包，你下载最新代码就可以。

**Comment by xiemeng99** [comment]
release下呗，毕竟jitpack方便

**Comment by xiemeng99** [comment]
对了，还有个问题咨询，第一行的ABCDE和表名可以隐藏的吗

**Comment by huangyanbin** [comment]
表名隐藏忘记加了，小功能，下次更新加上。X序列可以隐藏 ，table里面有个TableConfig对象，有很多设置， 其中setShowXSequence X序列隐藏。这版发布主要增加支持二维数组，可以用于日程表和电影选坐等等功能支持。

**Comment by xiemeng99** [comment]
厉害厉害，类似电影选座功能我后期也有场景需要，嗯嗯，我也发现里面方法比较多，慢慢熟悉，感谢
