### ISSUE TITLE
能否加一个隐藏表标题的功能；

### ISSUE THREAD

**Issue by zhouzhuo810** [huangyanbin/smartTable#6]
有时候表标题不一定需要显示在控件内

**Comment by huangyanbin** [comment]
在最新代码已经加上了，还需要修复其他几个小问题，一起发布新版

**Comment by zhouzhuo810** [comment]
好的

**Comment by zhouzhuo810** [comment]
我试了最新代码的隐藏标题，好像点击后，内容会上下切换。滑动就会不停切换。看着像闪烁。

**Comment by huangyanbin** [comment]
你指的说的列标题隐藏还是表格标题隐藏？

**Comment by zhouzhuo810** [comment]
表格标题

**Comment by zhouzhuo810** [comment]
我用的注解模式

**Comment by huangyanbin** [comment]
好的，我先看看

**Comment by zhouzhuo810** [comment]
`
@SmartTable(name = "ReportContentEntity")
public class ReportContentEntity {
    @SmartColumn(id = 1, name = "机台")
    private String macName;
    @SmartColumn(id = 2, name = "计划单号")
    private String planNo;
    @SmartColumn(id = 3, name = "产品名称")
    private String productName;
    @SmartColumn(id = 4, name = "生产数量")
    private int produceQty;

    public String getMacName() {
        return macName;
    }

    public void setMacName(String macName) {
        this.macName = macName;
    }

    public String getPlanNo() {
        return planNo;
    }

    public void setPlanNo(String planNo) {
        this.planNo = planNo;
    }

    public String getProductName() {
        return productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public int getProduceQty() {
        return produceQty;
    }

    public void setProduceQty(int produceQty) {
        this.produceQty = produceQty;
    }
}

`
`
        List<ReportContentEntity> contents = new ArrayList<>();
        for (int i = 0; i < 10; i++) {
            ReportContentEntity entity = new ReportContentEntity();
            entity.setMacName(i + "#");
            entity.setPlanNo(System.currentTimeMillis() + "");
            entity.setProductName("瓶盖");
            entity.setProduceQty(1045);
            contents.add(entity);
        }
        table.getConfig().setContentBackgroundFormat(new BaseBackgroundFormat<CellInfo>() {
            @Override
            public int getBackGroundColor() {
                return ContextCompat.getColor(ReportActivity.this, R.color.colorGrayBg);
            }

            @Override
            public boolean isDraw(CellInfo cellInfo) {
                return cellInfo.position % 2 == 0;
            }
        });
        table.getConfig().setShowTableTitle(true);
        table.setZoom(true);
        table.setData(contents);
`
这是我的测试代码

**Comment by zhouzhuo810** [comment]
@SmartTable(name = "ReportContentEntity")
public class ReportContentEntity {
    @SmartColumn(id = 1, name = "机台")
    private String macName;
    @SmartColumn(id = 2, name = "计划单号")
    private String planNo;
    @SmartColumn(id = 3, name = "产品名称")
    private String productName;
    @SmartColumn(id = 4, name = "生产数量")
    private int produceQty;

    public String getMacName() {
        return macName;
    }

    public void setMacName(String macName) {
        this.macName = macName;
    }

    public String getPlanNo() {
        return planNo;
    }

    public void setPlanNo(String planNo) {
        this.planNo = planNo;
    }

    public String getProductName() {
        return productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public int getProduceQty() {
        return produceQty;
    }

    public void setProduceQty(int produceQty) {
        this.produceQty = produceQty;
    }
}


        List<ReportContentEntity> contents = new ArrayList<>();
        for (int i = 0; i < 10; i++) {
            ReportContentEntity entity = new ReportContentEntity();
            entity.setMacName(i + "#");
            entity.setPlanNo(System.currentTimeMillis() + "");
            entity.setProductName("瓶盖");
            entity.setProduceQty(1045);
            contents.add(entity);
        }
        table.getConfig().setContentBackgroundFormat(new BaseBackgroundFormat<CellInfo>() {
            @Override
            public int getBackGroundColor() {
                return ContextCompat.getColor(ReportActivity.this, R.color.colorGrayBg);
            }

            @Override
            public boolean isDraw(CellInfo cellInfo) {
                return cellInfo.position % 2 == 0;
            }
        });
        table.getConfig().setShowTableTitle(true);
        table.setZoom(true);
        table.setData(contents);


这是测试代码

**Comment by zhouzhuo810** [comment]
把setShowTableTitle设置为false就会闪烁

**Comment by huangyanbin** [comment]
我晚上去看下，现在上班有事。

**Comment by zhouzhuo810** [comment]
嗯

**Comment by huangyanbin** [comment]
已经修复了，1.5.1, 你试试

**Comment by zhouzhuo810** [comment]
没毛病,现在离我的需求只差：行高和列宽用手指控制了，不知道兄弟有没有解决方案。如下图：
![test](https://user-images.githubusercontent.com/15272555/34931524-396d35b8-fa0a-11e7-9cbb-c27d2ea07049.png)

**Comment by zhouzhuo810** [comment]
类似于这个https://github.com/lovebzhou/HBExcelView

**Comment by huangyanbin** [comment]
要是我自己改，肯定可以实现，我主要怕我加入了破坏了现有代码逻辑。这个需求等级并不高。你可以试着改下代码。

**Comment by zhouzhuo810** [comment]
嗯。我试试吧，主要是你的代码不太熟悉。项目有比较急，所以才问你

**Comment by huangyanbin** [comment]
我感觉你们需求好变态啊，手机来移位感觉没意义

**Comment by zhouzhuo810** [comment]
我也觉得意义不大啊，产品执意如此，而且他就是看了wps有这个功能；

**Comment by zhouzhuo810** [comment]
嗯 IOS找了一个Demo实现了，我不能丢安卓的脸啊
