### ISSUE TITLE
一个小问题

### ISSUE THREAD

**Issue by mrchenmo** [huangyanbin/smartTable#7]
在竖向滑动表格的时候能不能禁止 表格的横向滑动，在横向滑动的时候禁止表格的竖向滑动。这样在滑动的时候表格就不会抖动了。算是一个小优化QAQ

**Comment by huangyanbin** [comment]
您好，滑动表格抖动好像不是因为横向和竖向滑动的冲突，之前没有考虑到数据量很少的时候，临界值有问题，导致会抖动。我初步修复了该bug.后续继续优化。
