### ISSUE TITLE
在dialog中使用崩溃

### ISSUE THREAD

**Issue by LittleRobotRoad** [huangyanbin/smartTable#93]
has leaked window DecorView@b2d5e4[] that was originally added here

**Comment by huangyanbin** [comment]
你下载源码，改下那里`private static Activity getActivity(Context context) {
		// Gross way of unwrapping the Activity so we can get the FragmentManager
		while (context instanceof ContextWrapper) {
			if (context instanceof Activity) {
				return (Activity)context;
			}
			context = ((ContextWrapper)context).getBaseContext();
		}
		throw new IllegalStateException("The MediaRouteButton's Context is not an Activity.");
	}`
