### ISSUE TITLE
结束活动后报错android.view.ContextThemeWrapper cannot be cast to android.app.Activity

### ISSUE THREAD

**Issue by Edouardliang** [huangyanbin/smartTable#95]
以下为出错activity源码，不懂是什么原因导致的，但通过百度，修改了作者的部分源码解决了
public class Sign_in extends AppCompatActivity implements View.OnClickListener,onDatasready {
    private Button compelet,sign;
    private EditText datecheck;
    private ImageButton back;
    private SmartTable<SignBean> table;
    private getArryList tabledatas=SignBean.getSignbean();

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        supportRequestWindowFeature(Window.FEATURE_NO_TITLE);
        setContentView(R.layout.activity_sign_in);
        init();
    }
    private void init(){
        back=(ImageButton)findViewById(R.id.back_button);
        compelet=(Button)findViewById(R.id.queding);
        datecheck=(EditText)findViewById(R.id.datecheck);
        sign=(Button)findViewById(R.id.sign);
        table=(SmartTable)findViewById(R.id.table);
        sign.setOnClickListener(this);
        back.setOnClickListener(this);
        compelet.setOnClickListener(this);
        SignBean.getSignbean().setContext(this);
        SignBean.getSignbean().onDatasreadyListener(this);
        EditListener();
        changebutton();
    }

    @Override
    public void onClick(View view){
        switch (view.getId()){
            case R.id.back_button:
                finish();
                break;
            case R.id.queding:
                final String date=datecheck.getText().toString();
                if(date.equals("")){
                    Toast.makeText(this,"请选择搜索日期",Toast.LENGTH_SHORT).show();
                }else{
                    new Thread(new Runnable() {
                        @Override
                        public void run() {
                            SignBean.getSignbean().setUpsign(date);
                        }
                    }).start();
                }
                break;
            case R.id.sign:
                sign();
                break;
        }
    }

    private void EditListener(){
        datecheck.setOnTouchListener(new View.OnTouchListener() {
            @Override
            public boolean onTouch(View view, MotionEvent motionEvent) {
                if (motionEvent.getAction() == MotionEvent.ACTION_DOWN) {
                    showDatePickDlg();
                    return true;
                }
                return false;
            }
        });
        datecheck.setOnFocusChangeListener(new View.OnFocusChangeListener() {
            @Override
            public void onFocusChange(View view, boolean b) {
                if(datecheck.hasFocus()){
                    showDatePickDlg();
                }
            }
        });
    }

    private void showDatePickDlg(){
        Calendar calendar=Calendar.getInstance();
        DatePickerDialog datePickerDialog=new DatePickerDialog(Sign_in.this, new DatePickerDialog.OnDateSetListener() {
            @Override
            public void onDateSet(DatePicker datePicker, int i, int i1, int i2) {
                int moth=i1+1;
                Sign_in.this.datecheck.setText(i+"/"+moth+"/"+i2);
            }
        },calendar.get(Calendar.YEAR),calendar.get(Calendar.MONTH),calendar.get(Calendar.DAY_OF_MONTH));
        datePickerDialog.show();
    }

    private void sign(){
        SharedPreferences sharedPreferences=getSharedPreferences("sign",MODE_PRIVATE);
        boolean state=sharedPreferences.getBoolean("sign",false);
        if(state){
            sign_out();
            SignBean.getSignbean().sign(this,"签退");
            changebutton();
        }else{
            sign_in();
            SignBean.getSignbean().sign(this,"签到");
            changebutton();
        }
    }

    private void sign_in(){
        SharedPreferences sharedPreferences=getSharedPreferences("sign",MODE_PRIVATE);
        SharedPreferences.Editor editor=sharedPreferences.edit();
        editor.putBoolean("sign",true);
        editor.commit();
    }

    private void sign_out(){
        SharedPreferences sharedPreferences=getSharedPreferences("sign",MODE_PRIVATE);
        SharedPreferences.Editor editor=sharedPreferences.edit();
        editor.putBoolean("sign",false);
        editor.commit();
    }

    private void changebutton(){
        SharedPreferences sharedPreferences=getSharedPreferences("sign",MODE_PRIVATE);
        boolean state=sharedPreferences.getBoolean("sign",false);
        if(state){
            sign.setText("签退");
        }else{
            sign.setText("签到");
        }
    }

    @Override
    public void onDatasready(){
        List<Column> columns=new ArrayList<>();
        final Column<String> id=new Column<String>("工号","id");
        final Column<String> date=new Column<String>("日期","date");
        final Column<String> date_state=new Column<String>("备注","state");
        columns.add(id);columns.add(date);columns.add(date_state);
        TableData tableData=new TableData("签到表",tabledatas.getArryList(),columns);
        table.setTableData(tableData);
    }

}

解决方法：将core中的SmartTable类中onDetachedFromWindow方法改为
    @Override
    protected void onDetachedFromWindow() {
        super.onDetachedFromWindow();
        if (tableData != null && getContext() != null) {
            if ((scanForActivity(getContext())).isFinishing()) {
                release();
            }
        }
    }

并在类中添加scanForActivity方法：
    private static Activity scanForActivity(Context cont) {
        if (cont == null)
            return null;
        else if (cont instanceof Activity)
            return (Activity)cont;
        else if (cont instanceof ContextWrapper)
            return scanForActivity(((ContextWrapper)cont).getBaseContext());

        return null;
    }

借用CSDN上：https://blog.csdn.net/yaphetzhao/article/details/49639097 的解决方法

**Comment by huangyanbin** [comment]
嗯，之前没有考虑到在Dialog上情况。

**Comment by huangyanbin** [comment]
多谢老兄
